### ISSUE TITLE
configuration set-up issue

### ISSUE THREAD

**Issue by adonnini** [authenteq/java-bigchaindb-driver#74]
Hi,

I made some progress in processing a transaction from my Android application.

The latest issue is the following:

When I try to set up the configuration using

	  			BigchainDbConfigBuilder
				.baseUrl("https://test.bigchaindb.com/api/v1/")
  			        .addToken("app_id", "57b164b9")
	  			.addToken("app_key", "257ae1d1686bbe4ac702ba186172c5dd").setup();

as per instructions on the read page ,

The operation fails with the following error:

03-21 13:00:23.860: W/System.err(15558): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
03-21 13:00:23.861: W/System.err(15558): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
03-21 13:00:23.862: W/System.err(15558): 	at com.google.gson.Gson.fromJson(Gson.java:888)
03-21 13:00:23.862: W/System.err(15558): 	at com.google.gson.Gson.fromJson(Gson.java:853)
03-21 13:00:23.862: W/System.err(15558): 	at com.google.gson.Gson.fromJson(Gson.java:802)
03-21 13:00:23.862: W/System.err(15558): 	at com.google.gson.Gson.fromJson(Gson.java:774)
03-21 13:00:23.862: W/System.err(15558): 	at src.main.java.com.authenteq.util.JsonUtils.fromJson(JsonUtils.java:143)
03-21 13:00:23.862: W/System.err(15558): 	at src.main.java.com.authenteq.builders.BigchainDbConfigBuilder$Builder.setup(BigchainDbConfigBuilder.java:138)
03-21 13:00:23.863: W/System.err(15558): 	at com.android.commmanager.continuouslocationtrackingservice.UserAndPoiProcessing$ConnectToNetwork.doInBackground(UserAndPoiProcessing.java:12325)
03-21 13:00:23.863: W/System.err(15558): 	at com.android.commmanager.continuouslocationtrackingservice.UserAndPoiProcessing$ConnectToNetwork.doInBackground(UserAndPoiProcessing.java:12295)
03-21 13:00:23.864: W/System.err(15558): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
03-21 13:00:23.864: W/System.err(15558): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-21 13:00:23.865: W/System.err(15558): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
03-21 13:00:23.865: W/System.err(15558): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-21 13:00:23.865: W/System.err(15558): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-21 13:00:23.865: W/System.err(15558): 	at java.lang.Thread.run(Thread.java:764)
03-21 13:00:23.866: W/System.err(15558): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
03-21 13:00:23.866: W/System.err(15558): 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
03-21 13:00:23.866: W/System.err(15558): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
03-21 13:00:23.867: W/System.err(15558): 	... 14 more
0

What am I doing wrong?

Thanks,

Alex Donnini

**Comment by adonnini** [comment]
Hi,

I could be wrong but I think that in order to resolve the problem reported above, the following change needs to be made to BigchainDbConfigBuilder.java:

Line 

NetworkUtils.sendGetRequest(this.baserUrl + "/api" + BigchainDbApi.API_VERSION).body().string(),

should be replaced with

NetworkUtils.sendGetRequest("{" + this.baserUrl + "/api" + BigchainDbApi.API_VERSION).body().string() + "}",

Thanks,

Alex Donnini

**Comment by adonnini** [comment]
Hi,

It looks like the BigChainDBGlobals.setApiEndpoints call in BigchainDbConfigBuilder.java which seems to work for me is:

				BigChainDBGlobals.setApiEndpoints(JsonUtils.fromJson(
						NetworkUtils.sendGetRequest(this.baserUrl).body().string(),
						ApiEndpoints.class));

where baseUrl is

https://test.bigchaindb.com/api/v1/

I do realize that 

				BigChainDBGlobals.setApiEndpoints(JsonUtils.fromJson(
					NetworkUtils.sendGetRequest(this.baserUrl + "/api" + BigchainDbApi.API_VERSION).body().string(),
						ApiEndpoints.class));

should also work with baseUrl set to 

https://test.bigchaindb.com
